### ISSUE TITLE
Download doesn't work on Safari

### ISSUE THREAD

**Issue by tedtoal** [atoponce/webpassgen#10]
I downloaded the code and opened index.html in Safari on OSX.  Forms show up where I can select an option and press the "Generate" button, but clicking that button does nothing.  I have javascript enabled.  I'm suspecting that Safari by default blocks file:// javascript or something like that.  If this is a common problem with Safari and this web page, it would be nice if the README file mentioned it and how to fix it.

**Comment by atoponce** [comment]
It appears that Safari doesn't like "async" when using "crossorigin". I'll dig deeper, but removing "async" from the list of <script> tags does the job.
