### ISSUE TITLE
Instructions to run locally on iOS devices

### ISSUE THREAD

**Issue by metbril** [atoponce/webpassgen#8]
Instructions to run the password generator locally on an iOS device from the ZIP file downloaded directly from GitHub.

Prerequisites:
- Install the [Readdle Documents]() app on your iOS device 

Workflow:

Open the Safari browser.
Open the demo site at https://ae7.st/g/.
Scroll to the bottom and click the download link (insert screenshot). 
![a248e918-0d96-4c26-a1db-109dabb9971b](https://user-images.githubusercontent.com/559346/35161734-5ed9485c-fd41-11e7-9107-ae0f1e8a00eb.jpeg)

This will open the [releases page from the GitHub repository](https://github.com/atoponce/webpassgen/releases/).
Click the link that says 'Source code (zip)'.
![2b390346-1a9d-4358-864b-84ba5556cdbd](https://user-images.githubusercontent.com/559346/35161789-85cce482-fd41-11e7-9cac-eab03722165a.jpeg)

This will open the zip file in the Documents app.
Click the zip file, to expand it into it's own folder.
![f72ead48-e7bc-4e36-9ab1-e4ba7874a199](https://user-images.githubusercontent.com/559346/35161881-d18aa1fc-fd41-11e7-8d69-919d0d970386.jpeg)

Move into the folder and click the Index file. This will open the local copy of the file.
![d7f8ceb6-2e3c-4716-a418-7f987b33167f](https://user-images.githubusercontent.com/559346/35161935-011c9cfe-fd42-11e7-96d3-bc71a1823da9.jpeg)
![c4928020-f01e-4fa4-a5e0-ce7fcd485283](https://user-images.githubusercontent.com/559346/35161936-014ac91c-fd42-11e7-8c1a-a8a560fe2d75.png)

**Comment by atoponce** [comment]
[Added to the wiki](https://github.com/atoponce/webpassgen/wiki/Offline-iOS-Documentation), with some language editing and reflow work. Thanks for the work on this!
