### ISSUE TITLE
Entropy toolbar text problems

### ISSUE THREAD

**Issue by atoponce** [atoponce/webpassgen#9]
In my Chromium browser on one desktop, I see the following:

![entropy](https://user-images.githubusercontent.com/699572/37670406-d46eeb1e-2c2e-11e8-8470-a0db599d17b6.png)

**Comment by atoponce** [comment]
Increasing the width from 55 px -> 60 px for `#entropy-toolbar input[type="radio"] + label` certainly works, but then creates 2 columns by 3 rows in the mobile interface.

Alternatively, the width could remain 55 px and the font-size scaled down to 12 pt, then everything looks good.

But how would other font faces look in both desktop and mobile? I have a feeling I'm chasing down a rabbit hole.

**Comment by 5moufl** [comment]
(re)move the -bits part?

**Comment by atoponce** [comment]
Yeah, that's certainly the lowest-hanging fruit.

**Comment by atoponce** [comment]
Closed with f9e8266.
